### ISSUE TITLE
Perhaps a false positive warning with upcoming ggplot2 release

### ISSUE THREAD

**Issue by teunbrand** [jbdorey/BeeBDC#9]
Hello there,

We have been preparing a new release of ggplot2 and during a reverse dependency check, it *appeared* that BeeBDC would be broken. However, I think this might be a false positive because the test that was flagged has been disabled already in the lines below:

https://github.com/jbdorey/BeeBDC/blame/2014ec3db2c1c6ea15f0fd20ad8561a8d5152cec/tests/testthat/test-summaryMaps.R#L29-L31

I also locally tested BeeBDC against the ggplot2 release candidate and didn't find any issues. However, according to the CRAN mirror that test is still active, see: https://github.com/cran/BeeBDC/blob/master/tests/testthat/test-summaryMaps.R

If anything, please consider this issue a heads up that CRAN *might* start complaining about some failing tests when the new ggplot2 version is released. 

If you'd like to be 100% sure and test the code changes with the release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The release of ggplot2 3.5.0 is scheduled for the 12th of Februari. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588.

P.S. bees are amazing

**Comment by jbdorey** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Hey Teun,Thanks so much for the heads up! I’ve removed that line and will continue to monitor. My next planned update will be after the 12th of February (as I’ll have access to some ARM and Windows machines to better test the package). I’ll make sure that everything works well!And thank you, bees are amazing. So is ggplot2!   
        
     
     
        
            Dr James Dorey - Adjunct Lecturer at Flinders UniversityJamesDoreyPhotography.com.au    Mobile: +61 401 421 073
                 

        
     
 On 17 January 2024 at 12:49:38 am, Teun van den Brand ***@***.***) wrote: 
Hello there,
We have been preparing a new release of ggplot2 and during a reverse dependency check, it appeared that BeeBDC would be broken. However, I think this might be a false positive because the test that was flagged has been disabled already in the lines below:
https://github.com/jbdorey/BeeBDC/blame/2014ec3db2c1c6ea15f0fd20ad8561a8d5152cec/tests/testthat/test-summaryMaps.R#L29-L31
I also locally tested BeeBDC against the ggplot2 release candidate and didn't find any issues. However, according to the CRAN mirror that test is still active, see: https://github.com/cran/BeeBDC/blob/master/tests/testthat/test-summaryMaps.R
If anything, please consider this issue a heads up that CRAN might start complaining about some failing tests when the new ggplot2 version is released.
If you'd like to be 100% sure and test the code changes with the release candidate, you can install it with the code below:
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
The release of ggplot2 3.5.0 is scheduled for the 12th of Februari. The progress of the release can be tracked in tidyverse/ggplot2#5588.
P.S. bees are amazing
